[package]
name = "ddns-updater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.27", features = ["full"] }
reqwest = "0.11.6"
anyhow = "1.0.51"
dotenvy = "0.15.7"
