[[domains]]
domain = "example.com"
subdomain = "@"
domain_type = "Namecheap"
password = "password"

[[domains]]
domain = "example.org"
domain_type = "Google"
username = "username"
password = "password"
